version: '3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: conference_app_user
      POSTGRES_PASSWORD: 5UvUwY3xRH86xXhx
      POSTGRES_DB: conference_app
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      PORT: 80
      JWT_SECRET: jfslkdjflaksjflkljfsl
      PGHOST: host.docker.internal
      PGPORT: 5432
      PGAPPNAME: Conference GO!
      WAIT_HOSTS: postgres:5432

      # Thes values are the same as below
      PGDATABASE: conference_app
      PGUSER: conference_app_user
      PGPASSWORD: 5UvUwY3xRH86xXhx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    ports:
      - '8080:80'
